### ISSUE TITLE
Fail to overwrite the default variables

### ISSUE THREAD

**Issue by zzdjk6** [soulrolll/silverstripe-bootstrap-boilerplate-theme#6]
The `styles.scss` put the customized `_variables` after importing the whole `bootstrap` libraries, which makes the overwriting not work.

According to https://getbootstrap.com/docs/4.1/getting-started/theming/:

> Variable overrides within the same Sass file can come before or after the default variables.
> However, when overriding across Sass files, your overrides must come before you import Bootstrap’s Sass files.

The correct way to overwrite the variables is to put the custom ones around just this line (either before or after), but need to make sure it happens before any other `@import`.

https://github.com/soulroll/silverstripe-bootstarter/blob/51c6ea3cf6edd78e0fc16e4a5c8b003b4d997bc6/src/scss/bootstrap/_bootstrap.scss#L9

For example:

```scss
@import "../../../node_modules/bootstrap/scss/functions";
@import "../../../node_modules/bootstrap/scss/variables";
@import "variables";
@import "../../../node_modules/bootstrap/scss/mixins";
...
```

Only by doing so, other parts of Bootstrap such as mixins can use the overwritten values. (for example, the `$grid-breakpoint` affects a lot of other parts)

**Comment by soulroll** [comment]
Merged, cheers Thor
