### ISSUE TITLE
Favicon template is missing

### ISSUE THREAD

**Issue by ivoba** [soulrolll/silverstripe-bootstrap-boilerplate-theme#8]
https://github.com/soulroll/silverstripe-bootstarter/blob/master/templates/Page.ss#L16

but the template is missing and results in error

> None of the following templates could be found: Array ( [0] => Array ( [type] => Includes [0] => Favicon ) [1] => Favicon ) in themes "Array ( [0] => $public [1] => $default ) "

**Comment by soulroll** [comment]
Should be fixed in the latest update
